# This workflow runs on every push and checks whether everything looks good

name: Quick check

on:
  push:
    tags:
      - "!v*"
    branches:
      - "*"

jobs:
  quick_check:
    env:
      TEST_TARGET: /tmp-tests
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        include:
          - template: cli
            clap: true
          - template: cli
            clap: false
          - template: lib
            # clap: n_a
          - template: parity-lib
            # clap: n_a

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Cache Dependencies & Build Outputs
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/checkout@v3

      - name: Install tollin
        run: |
          cargo install cargo-generate
          cargo generate --version

      - name: Generate test project for ${{ matrix.template }}
        run: |
          cargo generate --path ${{ matrix.template }} \
            --destination $TEST_TARGET/${{ matrix.template }}-${{ matrix.clap }} \
            --name "test-${{ matrix.template }}-${{ matrix.clap }}" \
            --define clap=${{ matrix.clap }}

      - name: Cargo fmt for ${{ matrix.template }} / ${{ matrix.clap }}
        working-directory: $TEST_TARGET/${{ matrix.template }}-${{ matrix.clap }}
        run: cargo fmt --all -- --check

      - name: Cargo clippy for ${{ matrix.template }} / ${{ matrix.clap }}
        working-directory: $TEST_TARGET/${{ matrix.template }}-${{ matrix.clap }}
        run: cargo clippy -- -D warnings

      - name: Cargo test for ${{ matrix.template }} / ${{ matrix.clap }}
        working-directory: $TEST_TARGET/${{ matrix.template }}-${{ matrix.clap }}
        run: cargo test

      - name: Cargo check for ${{ matrix.template }} / ${{ matrix.clap }}
        working-directory: $TEST_TARGET/${{ matrix.template }}-${{ matrix.clap }}
        run: cargo check
